export type CharacterEntry = {
  name: string;
  testament: "OT" | "NT";
};

export const CHARACTERS: CharacterEntry[] = [
  // Old Testament
  { name: "Adam", testament: "OT" },
  { name: "Eve", testament: "OT" },
  { name: "Noah", testament: "OT" },
  { name: "Abraham", testament: "OT" },
  { name: "Sarah", testament: "OT" },
  { name: "Isaac", testament: "OT" },
  { name: "Rebekah", testament: "OT" },
  { name: "Jacob", testament: "OT" },
  { name: "Rachel", testament: "OT" },
  { name: "Joseph", testament: "OT" },
  { name: "Moses", testament: "OT" },
  { name: "Aaron", testament: "OT" },
  { name: "Miriam", testament: "OT" },
  { name: "Joshua", testament: "OT" },
  { name: "Deborah", testament: "OT" },
  { name: "Gideon", testament: "OT" },
  { name: "Samson", testament: "OT" },
  { name: "Ruth", testament: "OT" },
  { name: "Hannah", testament: "OT" },
  { name: "Samuel", testament: "OT" },
  { name: "Saul", testament: "OT" },
  { name: "David", testament: "OT" },
  { name: "Solomon", testament: "OT" },
  { name: "Elijah", testament: "OT" },
  { name: "Elisha", testament: "OT" },
  { name: "Isaiah", testament: "OT" },
  { name: "Jeremiah", testament: "OT" },
  { name: "Ezekiel", testament: "OT" },
  { name: "Daniel", testament: "OT" },
  { name: "Esther", testament: "OT" },
  { name: "Nehemiah", testament: "OT" },
  { name: "Job", testament: "OT" },
  { name: "Jonah", testament: "OT" },

  // New Testament
  { name: "Jesus Christ", testament: "NT" },
  { name: "Mary, Mother of Jesus", testament: "NT" },
  { name: "Joseph of Nazareth", testament: "NT" },
  { name: "John the Baptist", testament: "NT" },
  { name: "Simon Peter", testament: "NT" },
  { name: "Andrew", testament: "NT" },
  { name: "James, Son of Zebedee", testament: "NT" },
  { name: "John the Apostle", testament: "NT" },
  { name: "Matthew", testament: "NT" },
  { name: "Thomas", testament: "NT" },
  { name: "Paul", testament: "NT" },
  { name: "Barnabas", testament: "NT" },
  { name: "Mary Magdalene", testament: "NT" },
  { name: "Martha", testament: "NT" },
  { name: "Lazarus", testament: "NT" },
  { name: "Stephen", testament: "NT" },
  { name: "Timothy", testament: "NT" },
  { name: "Luke", testament: "NT" },
];
