#!/usr/bin/env bash
# Regenerates supabase/seed.sql (loaded by `npm run db:reset`) from the local
# database: the content tables plus the PUBLIC-DOMAIN Bibles only (Judson 1840,
# KJV). Mizo, AI data, embeddings and user data are left out — seed those with
# their own scripts (db:seed-bible:mizo, db:generate-embeddings).
set -euo pipefail
cd "$(dirname "$0")/.."
DB_CONTAINER=$(docker ps --format '{{.Names}}' | grep '^supabase_db_myanmarbible-web$')
OUT=supabase/seed.sql
PSQL=(docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -At -v ON_ERROR_STOP=1)
{
  cat <<'HDR'
--
-- Myanmar Bible seed data — generated by scripts/dump-seed.sh (do not edit by hand).
-- Content tables + public-domain Bibles (Judson 1840, KJV).
--
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

HDR
  docker exec "$DB_CONTAINER" pg_dump -U postgres -d postgres --data-only --inserts --no-owner --no-privileges \
    -t public.blog_posts -t public.characters -t public.lessons -t public.podcast_episodes -t public.questions \
    | grep -v '^SET \|^SELECT pg_catalog.set_config\|^-- Dumped\|^-- PostgreSQL database dump'
  echo
  echo "-- Bibles (public domain only)"
  "${PSQL[@]}" -c "select format('INSERT INTO public.translations (id, code, name_en, name_my, language, is_default, is_licensed, license_info, source_url, created_at) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L);', id, code, name_en, name_my, language, is_default, is_licensed, license_info, source_url, created_at) from public.translations where code in ('judson', 'kjv') order by code"
  "${PSQL[@]}" -c "select format('INSERT INTO public.books (id, translation_id, book_number, name_en, name_my, abbreviation_en, abbreviation_my, testament, chapter_count, created_at) VALUES (%L, %L, %s, %L, %L, %L, %L, %L, %s, %L);', b.id, b.translation_id, b.book_number, b.name_en, b.name_my, b.abbreviation_en, b.abbreviation_my, b.testament, b.chapter_count, b.created_at) from public.books b join public.translations t on t.id = b.translation_id where t.code in ('judson', 'kjv') order by t.code, b.book_number"
  "${PSQL[@]}" -c "select format('INSERT INTO public.verses (id, book_id, chapter_number, verse_number, text, created_at, updated_at) VALUES (%L, %L, %s, %s, %L, %L, %L);', v.id, v.book_id, v.chapter_number, v.verse_number, v.text, v.created_at, v.updated_at) from public.verses v join public.books b on b.id = v.book_id join public.translations t on t.id = b.translation_id where t.code in ('judson', 'kjv') order by t.code, b.book_number, v.chapter_number, v.verse_number"
} > "$OUT"
echo "Wrote $OUT ($(du -h "$OUT" | cut -f1))"
